title: LinkedQL
description: SQL, evolved â€” A reactive, version-aware database client.
markdown: GFM
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark 
show_downloads: true
github:
  is_project_page: true
  repository_url: https://github.com/linked-db/linked-ql
url: "https://linked-db.github.io"
baseurl: "/linked-ql"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
