title: LinkedQL
description: SQL, evolved â€” A reactive, version-aware database client.
theme: jekyll-theme-cayman   # or jekyll-theme-slate
markdown: GFM
url: "https://linked-db.github.io"
baseurl: "/linked-ql"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
