title: LinkedQL
description: SQL, evolved â€” A reactive, version-aware database client.
remote_theme: pages-themes/slate@v0.2.0  # or pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
markdown: GFM
url: "https://linked-db.github.io"
baseurl: "/linked-ql"
